### ISSUE TITLE
Route policy rules are not added on boot in debian-like distros

### ISSUE THREAD

**Issue by grebokra** [C2Devel/c2-ec2-netutils#3]
## Route policy rules are not added on boot in debian-like distros.

Having route policy rules configured is vital for instances with multiple network interfaces, because rules specify which routing table will be used for sending response traffic based on dst ip of incoming traffic. If route policy rules are not configured, traffic coming to all interfaces is being sent through the primary interface according to default route in main table, and this leads to a lack of connectivity.

**Expected behavior:**
Route policy rules for non-primary interfaces are being added on boot.

**Actual behavior:**
Route policy rules are not added.

This behavior is caused by udev rule running script for adding route policy rules before the primary interface is configured. Primary interface should be configured before the script runs, because script relies on EC2 metadata, which is not available unless primary interface is up.

**Comment by grebokra** [comment]
#2 fixes this issue

**Comment by aeko-empt** [comment]
Fixed in https://github.com/C2Devel/c2-ec2-netutils/pull/2
