### ISSUE TITLE
Route tables for non-primary interfaces are not added on Debian 11 

### ISSUE THREAD

**Issue by grebokra** [C2Devel/c2-ec2-netutils#4]
## Route tables for non-primary interfaces are not added on Debian 11 

In PR #1 support for Debian 11 were introduced.
Everything works like on previous Debian versions, except for one thing -- script fails to add different route table numbers in different interface configs for network scripts.

**Expected behavior:**
Scripts generate configs for interfaces and use different route table numbers for interface specific routes.

**Actual behaviour:**
Scripts generate configs for interfaces and use the same route table with number 10000

This behavior is caused by a bug in the following `if` https://github.com/C2Devel/c2-ec2-netutils/blob/7b9fe0e0bf119b72d33f1cc83cfbe2fdf33a8ad7/ec2net-functions#L30-L39

It ensures that a unique route table number is used based on the interface name.
Since Debian 11 uses the ens* interface naming, this code does not generate a routing table number.

**Comment by grebokra** [comment]
This issue will be fixed in #2

**Comment by aeko-empt** [comment]
Fixed in https://github.com/C2Devel/c2-ec2-netutils/pull/2
