### ISSUE TITLE
Behavior change in grep 3.8 causes netutils scripts to malfunction

### ISSUE THREAD

**Issue by grebokra** [C2Devel/c2-ec2-netutils#5]
## Behavior change in grep 3.8 causes netutils scripts to malfunction

In version 3.8 grep was migrated to PCRE2 according to this commit:
`e0d39a9133e1507345d73ac5aff85f037f39aa54` https://git.savannah.gnu.org/cgit/grep.git/

In pcre2 any alpha-numeric character preceded by a backslash is treated as a character or sequence with a special meaning. In the case where the sequence has not been defined to be special, an error occurs. This seems to be different from pcre behavior, where the error does not occur and the backslash is ignored.

This behavior change affects some `grep -P` commands in netutils scripts and even in dpkg scripts.
Examples are:
- https://github.com/C2Devel/c2-ec2-netutils/blob/219a9f7a03d7507bf1bad22fac300123fb018a80/DEBIAN/postinst#L3
- https://github.com/C2Devel/c2-ec2-netutils/blob/219a9f7a03d7507bf1bad22fac300123fb018a80/ec2ifscan#L13

grep returns the following error:
```
# grep -P '^\ID=' /etc/os-release
grep: unrecognized character follows \
```
It looks like the backslash in this case was not needed and now it even causes an error.

grep version: `grep (GNU grep) 3.8` on `Ubuntu 23.04 (Lunar Lobster)`

**Comment by aeko-empt** [comment]
Fixed in pr:https://github.com/C2Devel/c2-ec2-netutils/pull/6
