### ISSUE TITLE
`NetworkManager` with `ifcfg-rh` doesn't like routes with specified `proto`

### ISSUE THREAD

**Issue by grebokra** [C2Devel/c2-ec2-netutils#7]
On systems with the `initscripts` package controlling the network, such as RHEL 7, it was normal to use `proto kernel` in routes in the configurations `/etc/sysconfig/network-scripts/route-*`, because they were used literally by `network` initscript. On systems with `NetworkManager`, these configurations are interpreted by the `ifcfg-rh` plugin, and it seems to not allow specific`proto` and instead prefers nothing (which means the `static` proto will be used).

c2-ec2-netutils for rhel generate route configs with routes with `proto kernel` in them.
https://github.com/C2Devel/c2-ec2-netutils/blob/6505e30dd0e402579afd6736ab856e81062bc1a3/ec2net-functions#L118-L121

This causes a warning on RHEL8-9:
```
NetworkManager[756]: <warn>  [1685325176.7685] ifcfg-rh:     ignoring invalid route at "        10.222.16.0/20 dev eth1 proto kernel scope link src 10.222.16.4 table 10001" (/etc/sysconfig/network-scripts/route-eth1:2): Unrecognized argument ("to" is duplicate or "proto" is garbage)
```
And routes are applied with `proto static`:
```
~# ip r s t 10001
default via 10.222.16.1 dev eth1 proto static metric 104 
10.222.16.1 dev eth1 proto static scope link metric 104 
~#
```
On Fedora 38 (aka RHEL 10) this causes the same warning:
```
NetworkManager[541]: <warn>  [1685325497.1294] ifcfg-rh:     ignoring invalid route at "        10.222.16.0/20 dev eth1 proto kernel scope link src 10.222.16.4 table 10001" (/etc/sysconfig/network-scripts/route-eth1:2): Unrecognized argument ("to" is duplicate or "proto" is garbage)
```
But the routes are not applied at all:
```
~# ip r s t 10001
default via 10.222.16.1 dev eth1 proto static metric 104 
~#
```

**Comment by aeko-empt** [comment]
Fixed in pr:https://github.com/C2Devel/c2-ec2-netutils/pull/8
